# -*- coding: utf-8 -*-
"""AppDesign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Wtv4KjV1O9UjSpP3mplkhjmKv3oPsFM
"""

import re
import numpy as np
import streamlit as st
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from io import BytesIO
import os

COMMON_WORDS = {
    "ability", "able", "across", "adapt", "administer", "analysis", "analyze",
    "background", "building", "collaboration", "collaborate", "communication",
    "coordinate", "current", "daily", "demonstrated", "develop", "development",
    "ensure", "experienced", "familiar", "focus", "general", "including",
    "knowledge", "manage", "management", "multiple", "organized", "preferred",
    "prepare", "preparing", "process", "professional", "program", "provide",
    "required", "responsible", "results", "role", "seeking", "skills", "strong",
    "support", "supporting", "team", "using", "various", "well"
}

JOB_POSTING_NOISE = {
    "ability", "acceptable", "adaptability", "ads", "analysis skills", "analytical",
    "attention", "attention detail", "basic", "bachelor", "bachelor degree",
    "collaboration", "communications", "content", "creative", "data driven",
    "degree", "detail", "digital", "environment", "experience", "fast paced",
    "familiarity", "field", "journey", "knowledge", "manage", "management",
    "mindset", "multiple", "multiple priorities", "needed", "organizational",
    "preferred", "preferred qualifications", "priorities", "project management",
    "qualification", "qualifications", "related", "related field", "required",
    "required qualifications", "role", "skills", "skills needed", "spreadsheets",
    "storytelling", "strong", "strong data", "strong written", "teamwork",
    "understanding", "verbal", "written", "written verbal"
}

GENERIC_SINGLE_WORDS = {
    "app", "apps", "build", "building", "built", "company", "create", "design",
    "engineering", "feature", "features", "high", "ideal", "impact", "intern",
    "launch", "long", "mobile", "new", "people", "platform", "processes",
    "product", "products", "production", "program", "project", "projects",
    "scale", "scaling", "services", "ship", "shipping", "stack", "systems",
    "technical", "team", "tools", "users", "work", "world", "quality"
}

KNOWN_SKILL_PHRASES = {
    "google analytics", "google ads", "meta ads", "linkedin ads", "hubspot",
    "marketo", "mailchimp", "salesforce", "seo", "crm", "canva",
    "adobe creative suite", "social media", "content creation",
    "marketing analytics", "digital marketing", "marketing automation",
    "paid advertising", "graphic design", "data analysis",
    "project management", "creative suite", "swiftui", "swift concurrency",
    "ios", "ios developer platform", "app store connect", "typescript",
    "flask", "openapi", "buildkite", "bazel", "react", "sql", "python",
    "mobile design", "security best practices", "best practices",
    "mobile apps", "technical design"
}

MONTH_WORDS = {
    "january", "february", "march", "april", "may", "june", "july",
    "august", "september", "october", "november", "december", "summer",
    "fall", "spring", "winter"
}

ROLE_FAMILY_WORDS = {
    "accountant", "teacher", "psychologist", "therapist", "manager", "analyst",
    "engineer", "developer", "writer", "designer", "consultant", "coordinator",
    "specialist", "architect", "director", "controller", "nurse", "educator",
    "administrator", "recruiter", "assistant", "supervisor", "officer", "planner",
    "researcher", "technician", "scientist", "trainer", "advisor", "counselor",
    "counsellor", "social", "speech", "finance", "product", "marketing", "sales"
}

STRONG_VERBS = {
    "achieved", "administered", "architected", "automated", "built", "consolidated",
    "created", "decreased", "delivered", "deployed", "designed", "developed",
    "directed", "drove", "eliminated", "enabled", "engineered", "established",
    "exceeded", "executed", "expanded", "generated", "grew", "implemented",
    "improved", "increased", "integrated", "introduced", "launched", "led",
    "managed", "mentored", "migrated", "negotiated", "optimized", "orchestrated",
    "overhauled", "pioneered", "produced", "reduced", "refactored", "redesigned",
    "resolved", "revamped", "scaled", "secured", "shipped", "simplified",
    "spearheaded", "streamlined", "strengthened", "trained", "transformed",
    "upgraded"
}

WEAK_VERBS = {
    "aided", "assisted", "contributed", "did", "got", "handled", "helped",
    "involved", "made", "oversaw", "participated", "performed", "responsible",
    "served", "supported", "tasked", "used", "utilized", "was", "went", "worked"
}

METRIC_PATTERN = re.compile(
    r'\b\d[\d,]*\.?\d*\s*(%|percent|x\b|times|hours?|days?|weeks?|months?'
    r'|years?|users?|customers?|clients?|requests?|ms\b|seconds?|k\b|m\b|K\b|M\b'
    r'|projects?|teams?|members?|people|employees?|reports?|accounts?'
    r'|transactions?|records?|tickets?|applications?|endpoints?|points?)'
    r'|\$[\d,]+\.?\d*'
    r'|\d+[xX]\b'
    r'|\d+\+\s*(years?|users?|customers?|projects?|people|members?)'
    r'|\d+%',
    re.IGNORECASE
)

SECTION_HEADERS = {
    "summary": ["summary", "objective", "profile", "about", "about me",
                 "professional summary", "career summary", "career objective"],
    "experience": ["experience", "work experience", "employment", "work history",
                    "internship", "internships", "professional experience",
                    "relevant experience", "career history"],
    "skills": ["skills", "technical skills", "core competencies", "technologies",
               "tools", "proficiencies", "competencies", "areas of expertise",
               "technical proficiencies", "key skills"],
    "education": ["education", "academic background", "degrees", "academic",
                   "academic history"],
    "projects": ["projects", "personal projects", "portfolio", "selected projects",
                  "academic projects", "side projects", "key projects"],
}


# ─── File parsers ─────────────────────────────────────────────────────────────
def read_pdf(file_bytes):
    try:
        from pypdf import PdfReader
        reader = PdfReader(BytesIO(file_bytes))
        return "\n".join(p.extract_text() or "" for p in reader.pages).strip()
    except Exception:
        return ""

def read_docx(file_bytes):
    try:
        import docx
        doc = docx.Document(BytesIO(file_bytes))
        return "\n".join(p.text for p in doc.paragraphs).strip()
    except Exception:
        return ""

def clean_text(t):
    t = (t or "").replace("\x00", " ")
    return re.sub(r"\s+", " ", t).strip()

def normalize_title(title):
    title = re.sub(r"[^a-z0-9\s/&-]", " ", str(title).lower())
    noise_words = {
        "sr", "senior", "jr", "junior", "lead", "principal", "staff",
        "associate", "assistant", "intern", "ii", "iii", "iv", "i"
    }
    tokens = [tok for tok in title.split() if tok not in noise_words]
    return " ".join(tokens).strip() or str(title).strip()

def role_family_key(title):
    normalized = normalize_title(title)
    tokens = normalized.split()
    family = [tok for tok in tokens if tok in ROLE_FAMILY_WORDS]
    if family:
        return " ".join(family[:2])
    return " ".join(tokens[:2]) if tokens else normalized

def significant_terms(text, limit=12):
    tokens = re.findall(r"[a-z]{4,}", str(text).lower())
    filtered = []
    for token in tokens:
        if token in COMMON_WORDS:
            continue
        if token not in filtered:
            filtered.append(token)
        if len(filtered) == limit:
            break
    return set(filtered)

def keyword_quality(term):
    words = term.split()
    if not words:
        return False
    if len(words) > 3:
        return False
    if len(words) == 1 and words[0] in GENERIC_SINGLE_WORDS:
        return False
    if any(len(word) < 3 for word in words):
        return False
    if all(word in COMMON_WORDS for word in words):
        return False
    if len(words) == 2 and any(word in COMMON_WORDS for word in words):
        return False
    # Reject concatenated list items: multi-word terms that are just adjacent
    # items from comma-separated skill lists (TF-IDF artifacts).
    if len(words) == 3 and term not in KNOWN_SKILL_PHRASES:
        # If 2+ words are short standalone terms, likely a list artifact
        short_count = sum(1 for w in words if len(w) <= 6)
        if short_count >= 2:
            return False
    # Reject 2-word terms where both words are very short standalone terms
    if len(words) == 2 and all(len(w) <= 5 for w in words):
        if term not in KNOWN_SKILL_PHRASES:
            return False
    return True

def normalize_keyword_word(word):
    word = word.lower().strip()
    if word.endswith("ies") and len(word) > 4:
        return word[:-3] + "y"
    if word.endswith("s") and len(word) > 3 and not word.endswith("ss"):
        return word[:-1]
    return word

def has_redundant_words(term):
    normalized_words = [normalize_keyword_word(word) for word in term.split()]
    return len(normalized_words) != len(set(normalized_words))

def keyword_token_set(term):
    return {normalize_keyword_word(word) for word in term.split()}

def term_matches_text(term, text):
    text_lower = clean_text(text).lower()
    if term in text_lower:
        return True

    term_words = [normalize_keyword_word(word) for word in re.findall(r"[a-z0-9]+", term.lower())]
    text_words = {normalize_keyword_word(word) for word in re.findall(r"[a-z0-9]+", text_lower)}
    significant = [word for word in term_words if word not in COMMON_WORDS and word not in JOB_POSTING_NOISE]

    if not significant:
        return False
    if len(significant) == 1:
        return significant[0] in text_words

    matched = sum(1 for word in significant if word in text_words)
    return matched == len(significant)

def clean_keywords(keywords, limit=12):
    cleaned = []
    seen = set()
    for keyword in keywords:
        normalized = re.sub(r"[^a-z0-9\s/&-]", " ", str(keyword).lower())
        normalized = re.sub(r"\s+", " ", normalized).strip()
        if not normalized or normalized in seen:
            continue
        if not keyword_quality(normalized):
            continue
        if has_redundant_words(normalized):
            continue
        seen.add(normalized)
        cleaned.append(normalized)
        if len(cleaned) == limit:
            break
    return cleaned

def extract_known_skill_phrases(text):
    text_lower = clean_text(text).lower()
    found = []
    for phrase in sorted(KNOWN_SKILL_PHRASES, key=len, reverse=True):
        if phrase in text_lower and phrase not in found:
            found.append(phrase)
    return found

def keyword_specificity(term):
    words = term.split()
    score = 0
    if term in KNOWN_SKILL_PHRASES:
        score += 6
    if len(words) == 1 and len(term) <= 3:
        score += 4
    if any(char.isdigit() for char in term):
        score += 2
    if len(words) >= 2:
        score += 2
    if len(words) > 3:
        score -= 6
    if any(word not in COMMON_WORDS for word in words):
        score += 2
    if term in JOB_POSTING_NOISE:
        score -= 8
    if any(word in JOB_POSTING_NOISE for word in words):
        score -= 4
    if len(words) == 1 and words[0] in GENERIC_SINGLE_WORDS:
        score -= 8
    if any(word in MONTH_WORDS for word in words):
        score -= 8
    return score

def rank_keywords(candidates, limit):
    deduped = []
    seen = set()
    for candidate in candidates:
        normalized = re.sub(r"\s+", " ", candidate.strip().lower())
        if not normalized or normalized in seen:
            continue
        if has_redundant_words(normalized):
            continue
        seen.add(normalized)
        deduped.append(normalized)
    ranked = sorted(deduped, key=lambda term: (keyword_specificity(term), -len(term)), reverse=True)
    filtered = [term for term in ranked if keyword_specificity(term) > 0]

    selected = []
    selected_sets = []
    for term in filtered:
        term_set = keyword_token_set(term)
        skip = False
        for existing, existing_set in zip(selected, selected_sets):
            overlap_ratio = len(term_set & existing_set) / max(1, len(term_set))
            if overlap_ratio >= 0.8:
                skip = True
                break
            if term_set <= existing_set:
                skip = True
                break
            if existing_set < term_set and keyword_specificity(term) >= keyword_specificity(existing):
                idx = selected.index(existing)
                selected[idx] = term
                selected_sets[idx] = term_set
                skip = True
                break
        if skip:
            continue
        selected.append(term)
        selected_sets.append(term_set)
        if len(selected) == limit:
            break

    return selected

def is_structured_skill_line(line):
    line_lower = line.lower()
    if line_lower in JOB_POSTING_NOISE:
        return False
    if len(line.split()) > 18:
        return False
    return any(token in line_lower for token in [",", ":", "(", ")", " and ", "/"]) or any(
        phrase in line_lower for phrase in KNOWN_SKILL_PHRASES
    )

def extract_structured_terms(job_text):
    candidates = []
    for raw_line in str(job_text).splitlines():
        line = clean_text(raw_line)
        if not line or not is_structured_skill_line(line):
            continue
        lowered = line.lower()
        for phrase in extract_known_skill_phrases(line):
            if phrase not in candidates:
                candidates.append(phrase)
        for chunk in re.split(r"[:,;/()]|\band\b", lowered):
            chunk = clean_text(chunk.lower())
            if not chunk:
                continue
            if chunk in JOB_POSTING_NOISE:
                continue
            if any(word in MONTH_WORDS for word in chunk.split()):
                continue
            if len(chunk.split()) <= 3 and keyword_quality(chunk):
                candidates.append(chunk)
    return candidates

def sanitize_job_text(job_text):
    lines = []
    for raw_line in str(job_text).splitlines():
        line = clean_text(raw_line)
        if not line:
            continue
        if line.lower() in JOB_POSTING_NOISE:
            continue
        if line.endswith(":") and len(line.split()) <= 3:
            continue
        lines.append(line)
    return "\n".join(lines)

def distinct_phrases_from_text(text, limit=5):
    sentences = re.split(r"(?<=[.!?])\s+", clean_text(text))
    phrases = []
    for sentence in sentences:
        sentence = sentence.strip(" -")
        if len(sentence.split()) < 6:
            continue
        compact = re.sub(r"\s+", " ", sentence)
        if compact and compact not in phrases:
            phrases.append(compact)
        if len(phrases) == limit:
            break
    return phrases

SECTION_BREAK_WORDS = {
    "summary", "experience", "projects", "skills", "education", "certifications",
    "activities", "leadership", "awards", "contact"
}

def split_resume_segments(resume_text):
    text = str(resume_text).replace("\r", "\n")
    text = re.sub(r"\s*[|]\s*", " | ", text)
    text = re.sub(r"\s*[•]\s*", "\n• ", text)
    text = re.sub(r"\s+-\s+", "\n- ", text)
    text = re.sub(r"(?<!\n)(Summary|Experience|Projects|Skills|Education|Certifications|Activities|Leadership|Awards)\b", r"\n\1", text)
    segments = []
    for line in text.splitlines():
        line = clean_text(line)
        if line:
            segments.append(line)
    return segments

def looks_like_resume_header(line):
    line_lower = line.lower()
    if "@" in line_lower or "linkedin" in line_lower or "github" in line_lower:
        return True
    words = line.split()
    if len(words) <= 8 and all(word.lower().strip(":") in SECTION_BREAK_WORDS for word in words):
        return True
    return False

def extract_resume_bullets(resume_text, limit=6):
    bullets = []
    segments = split_resume_segments(resume_text)
    for line in segments:
        if looks_like_resume_header(line):
            continue
        if line.startswith(("-", "•", "*")):
            line = clean_text(line[1:])
        else:
            # If PDF extraction collapses formatting, keep only sentence-like segments.
            if len(line.split()) < 8:
                continue
            if line.split()[0].lower() in SECTION_BREAK_WORDS:
                continue
        if len(line.split()) < 6 or len(line.split()) > 28:
            continue
        bullets.append(line)
        if len(bullets) == limit:
            break
    return bullets

def audit_bullet(bullet_text):
    words = bullet_text.split()
    first_word = words[0].lower().rstrip(".,;:()") if words else ""
    strong = first_word in STRONG_VERBS
    weak = first_word in WEAK_VERBS
    has_metric = bool(METRIC_PATTERN.search(bullet_text))
    word_count = len(words)
    length_ok = 6 <= word_count <= 25

    issues = []
    if weak:
        issues.append("Starts with a weak verb — try a stronger one like 'Developed', 'Led', or 'Reduced'")
    elif not strong:
        issues.append("Consider starting with a strong action verb like 'Built', 'Implemented', or 'Designed'")
    if not has_metric:
        issues.append("No measurable outcome — add a number like 'reduced load time by 40%' or 'managed team of 5'")
    if word_count > 25:
        issues.append(f"Too long ({word_count} words) — trim to under 25 words for readability")
    elif word_count < 6:
        issues.append(f"Too short ({word_count} words) — add more context about impact")

    score = sum([strong, has_metric, length_ok])
    return {
        "text": bullet_text,
        "strong_verb": strong,
        "has_metric": has_metric,
        "length_ok": length_ok,
        "issues": issues,
        "score": score,
    }

def _match_section_header(line_text):
    """Check if a line is a resume section header. Returns section name or None."""
    # Strip decoration: bullets, dashes, colons, pipes, unicode dashes
    cleaned = re.sub(r"^[\s\-•*|─━═—–]+", "", line_text)
    cleaned = re.sub(r"[\s\-•*|─━═—–:]+$", "", cleaned)
    normalized = cleaned.lower().strip()
    # Skip if too many words (likely not a header)
    if len(normalized.split()) > 5:
        return None
    # Exact match against all keywords
    for section_name, keywords in SECTION_HEADERS.items():
        if normalized in keywords:
            return section_name
    # Partial/startswith match: "professional experience & internships" -> experience
    for section_name, keywords in SECTION_HEADERS.items():
        for kw in keywords:
            if normalized.startswith(kw) or kw.startswith(normalized):
                if len(normalized) >= 4:  # avoid matching too-short fragments
                    return section_name
    # Word-level match: if the line is short and contains a key section word
    section_core_words = {
        "experience": "experience", "skills": "skills", "education": "education",
        "projects": "projects", "summary": "summary", "objective": "summary",
        "competencies": "skills", "qualifications": "skills",
    }
    words = normalized.split()
    if len(words) <= 4:
        for word in words:
            word_clean = word.rstrip("s") if len(word) > 5 else word
            if word in section_core_words:
                return section_core_words[word]
            if word_clean in section_core_words:
                return section_core_words[word_clean]
    return None

def _extract_sections_by_lines(text):
    """Try to extract sections using line-by-line header detection."""
    lines = text.replace("\r", "\n").split("\n")
    sections = {}
    current_section = "header"
    current_lines = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        matched_section = _match_section_header(stripped)
        if matched_section and len(stripped.split()) <= 5:
            if current_lines:
                joined = " ".join(current_lines).strip()
                if joined:
                    sections[current_section] = sections.get(current_section, "") + " " + joined
            current_section = matched_section
            current_lines = []
        else:
            current_lines.append(stripped)

    if current_lines:
        joined = " ".join(current_lines).strip()
        if joined:
            sections[current_section] = sections.get(current_section, "") + " " + joined

    sections.pop("header", None)
    return sections

# Regex pattern to find section headers even in collapsed single-line text.
# Matches common ALL-CAPS or Title-Case headers that appear as word boundaries.
_SECTION_REGEX = re.compile(
    r'(?:^|\s)'
    r'(EXPERIENCE|WORK\s+EXPERIENCE|PROFESSIONAL\s+EXPERIENCE|RELEVANT\s+EXPERIENCE'
    r'|PROJECTS|PERSONAL\s+PROJECTS|ACADEMIC\s+PROJECTS|KEY\s+PROJECTS'
    r'|EDUCATION|ACADEMIC\s+BACKGROUND'
    r'|SKILLS|TECHNICAL\s+SKILLS|CORE\s+COMPETENCIES|KEY\s+SKILLS'
    r'|SUMMARY|PROFESSIONAL\s+SUMMARY|OBJECTIVE|CAREER\s+SUMMARY'
    r'|Experience|Work\s+Experience|Professional\s+Experience'
    r'|Projects|Personal\s+Projects'
    r'|Education|Academic\s+Background'
    r'|Skills|Technical\s+Skills|Core\s+Competencies'
    r'|Summary|Professional\s+Summary|Objective)'
    r'[\s:]*(?=\s|$)',
    re.MULTILINE
)

_HEADER_TO_SECTION = {
    "experience": "experience", "work experience": "experience",
    "professional experience": "experience", "relevant experience": "experience",
    "projects": "projects", "personal projects": "projects",
    "academic projects": "projects", "key projects": "projects",
    "education": "education", "academic background": "education",
    "skills": "skills", "technical skills": "skills",
    "core competencies": "skills", "key skills": "skills",
    "summary": "summary", "professional summary": "summary",
    "objective": "summary", "career summary": "summary",
}

def _extract_sections_by_regex(text):
    """Fallback: find section headers via regex, even in collapsed text."""
    matches = list(_SECTION_REGEX.finditer(text))
    if len(matches) < 2:
        return {}
    sections = {}
    for i, m in enumerate(matches):
        header_text = m.group(1).strip().rstrip(":").strip()
        section_name = _HEADER_TO_SECTION.get(header_text.lower())
        if not section_name:
            continue
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        content = text[start:end].strip()
        if content:
            sections[section_name] = sections.get(section_name, "") + " " + content
    return sections

def extract_sections(resume_text):
    # First try line-based detection (works well when newlines are preserved)
    sections = _extract_sections_by_lines(resume_text)
    if len(sections) >= 2:
        return sections
    # Fallback: regex-based detection for collapsed text or messy PDF extraction
    sections = _extract_sections_by_regex(resume_text)
    if len(sections) >= 2:
        return sections
    return {}

def score_sections(sections, job_text, model):
    if not sections:
        return {}
    section_names = list(sections.keys())
    section_texts = [sections[name] for name in section_names]
    all_texts = section_texts + [job_text]
    all_embs = model.encode(
        all_texts,
        normalize_embeddings=True,
        convert_to_numpy=True,
        show_progress_bar=False,
    )
    section_embs = all_embs[:-1]
    job_emb = all_embs[-1].reshape(1, -1)
    scores = {}
    for i, name in enumerate(section_names):
        sim = float(cosine_similarity(section_embs[i].reshape(1, -1), job_emb)[0][0])
        scores[name] = round(sim * 100, 1)
    return scores

def prioritize_missing_keywords(missing, resume_emb_vec, jobs_emb, jobs_meta, pool_size=50):
    if jobs_emb is None or resume_emb_vec is None or not missing:
        return [(kw, "LOW") for kw in missing]
    sims = cosine_similarity(resume_emb_vec.reshape(1, -1), jobs_emb)[0]
    pool_idx = np.argsort(sims)[::-1][:pool_size]
    pool_texts = [str(jobs_meta.iloc[i].get("master_text", "")).lower() for i in pool_idx]
    results = []
    for kw in missing:
        # Use lenient matching: for multi-word terms, check if any significant
        # word from the keyword appears in each job text
        kw_words = [normalize_keyword_word(w) for w in re.findall(r"[a-z0-9]+", kw.lower())]
        significant = [w for w in kw_words if w not in COMMON_WORDS and w not in JOB_POSTING_NOISE and len(w) >= 3]
        if not significant:
            results.append((kw, 0, "LOW"))
            continue
        count = 0
        for text in pool_texts:
            text_words = {normalize_keyword_word(w) for w in re.findall(r"[a-z0-9]+", text)}
            matched = sum(1 for w in significant if w in text_words)
            # Count as a hit if at least half the significant words appear
            if matched >= max(1, len(significant) // 2):
                count += 1
        if count >= 30:
            priority = "HIGH"
        elif count >= 15:
            priority = "MED"
        else:
            priority = "LOW"
        results.append((kw, count, priority))
    results.sort(key=lambda x: x[1], reverse=True)
    return results

def build_summary_suggestion(title, present, missing):
    title_text = normalize_title(title).title() if title and title != "Target Role" else "Professional"
    anchors = present[:2] + missing[:2]
    anchors = [term for idx, term in enumerate(anchors) if term and term not in anchors[:idx]]
    if not anchors:
        return f"{title_text} with experience delivering measurable results in cross-functional environments."
    if len(anchors) == 1:
        skills_text = anchors[0]
    elif len(anchors) == 2:
        skills_text = f"{anchors[0]} and {anchors[1]}"
    else:
        skills_text = ", ".join(anchors[:-1]) + f", and {anchors[-1]}"
    return f"{title_text} with experience in {skills_text}, delivering measurable results across technical and cross-functional work."

def build_bullet_rewrites(resume_text, present, missing, limit=3):
    source_bullets = extract_resume_bullets(resume_text, limit=limit * 2)
    anchor_terms = present[:2] + missing[:4]
    anchor_terms = [term for idx, term in enumerate(anchor_terms) if term and term not in anchor_terms[:idx]]
    rewrites = []

    for bullet in source_bullets:
        bullet_lower = bullet.lower()
        bullet_terms = [term for term in anchor_terms if any(word in bullet_lower for word in term.split())]
        selected_terms = bullet_terms[:2] if bullet_terms else anchor_terms[:2]
        if not selected_terms:
            continue
        before = bullet
        if len(before.split()) > 18:
            before = " ".join(before.split()[:18]) + "..."
        if len(selected_terms) == 1:
            after = f"{before} Reframed to emphasize **{selected_terms[0]}** while keeping the original accomplishment and measurable impact."
        else:
            after = f"{before} Reframed to emphasize **{selected_terms[0]}** and **{selected_terms[1]}** while keeping the original accomplishment and measurable impact."
        rewrites.append({"before": before, "after": after})
        if len(rewrites) == limit:
            break

    if not rewrites and anchor_terms:
        rewrites.append({
            "before": "Generic experience bullet",
            "after": f"Lead with **{anchor_terms[0]}**, describe the action you took, and end with the measurable result."
        })
    return rewrites

def role_summary(row):
    title = row.get("title", "This role")
    desc_phrases = distinct_phrases_from_text(row.get("description", ""), limit=1)
    if desc_phrases:
        sentence = desc_phrases[0]
        words = sentence.split()
        summary = " ".join(words[:24]) + ("..." if len(words) > 24 else "")
        return f"{title} focuses on {summary[0].lower() + summary[1:]}" if summary else title
    skills = clean_keywords(re.split(r"[,\n;/]+", row.get("skills", "")), limit=4)
    if skills:
        return f"{title} centers on {', '.join(skills)}."
    return f"{title} is one of the closest roles in the dataset for this resume."

def summarize_skills(skills_text, limit=5):
    raw_skills = re.split(r"[,\n;/]+", str(skills_text))
    cleaned = clean_keywords(raw_skills, limit=limit)
    return cleaned

def fit_bucket(label):
    if label in {"Excellent Match", "Good Match"}:
        return "Best Fits"
    if label == "Partial Match":
        return "Related Roles"
    return "Stretch Roles"

def build_match_reason(row, present, missing, raw_sim, kw_score):
    title = row.get("title", "This role")
    skills = summarize_skills(row.get("skills", ""), limit=4)
    reasons = []

    if raw_sim >= 0.46:
        reasons.append("the resume reads semantically close to this role's responsibilities")
    elif raw_sim >= 0.34:
        reasons.append("the resume overlaps with the role's overall domain language")
    else:
        reasons.append("there is at least some thematic overlap with the role")

    if present:
        reasons.append(f"it already reflects keywords like {', '.join(present[:3])}")
    elif skills:
        reasons.append(f"the role emphasizes skills such as {', '.join(skills[:3])}")

    if kw_score < 0.2 and missing:
        reasons.append(f"but it is still missing direct terms such as {', '.join(missing[:2])}")

    return f"{title} appears here because " + ", and ".join(reasons) + "."

def select_candidate_pool(similarities, pool_size=200):
    ranked_idx = np.argsort(similarities)[::-1]
    return ranked_idx[:min(pool_size, len(ranked_idx))]

def select_diverse_matches_from_ranked(ranked_matches, top_n):
    selected = []
    seen_titles = set()

    for match in ranked_matches:
        row = match["row"]
        title_key = normalize_title(row.get("title", ""))
        if title_key in seen_titles:
            continue
        selected.append(match)
        seen_titles.add(title_key)
        if len(selected) == top_n:
            return selected

    return selected

# ─── Model + data loading ─────────────────────────────────────────────────────
@st.cache_resource
def load_model():
    return SentenceTransformer("all-MiniLM-L6-v2")

@st.cache_resource
def load_job_data():
    try:
        jobs_emb = np.load("jobs_emb.npy")
        jobs_meta = pd.read_csv("jobs_metadata.csv").fillna("")
        return jobs_emb, jobs_meta
    except FileNotFoundError:
        return None, None

# ─── Keyword analysis ─────────────────────────────────────────────────────────
def top_keywords(job_text, resume_text, top_k=30):
    try:
        cleaned_job_text = sanitize_job_text(job_text)
        vec = TfidfVectorizer(stop_words="english", ngram_range=(1, 3), min_df=1)
        X = vec.fit_transform([cleaned_job_text, resume_text])
        terms = np.array(vec.get_feature_names_out())
        job_scores = X[0].toarray().ravel()
        top_idx = np.argsort(job_scores)[::-1][:top_k * 4]
        tfidf_terms = clean_keywords(terms[top_idx], limit=top_k * 4)
        explicit_terms = extract_known_skill_phrases(cleaned_job_text)
        structured_terms = extract_structured_terms(job_text)
        kw = rank_keywords(explicit_terms + structured_terms + tfidf_terms, limit=top_k)
        present = [k for k in kw if term_matches_text(k, resume_text) and k not in JOB_POSTING_NOISE]
        missing = [k for k in kw if not term_matches_text(k, resume_text) and k not in JOB_POSTING_NOISE]
        return present, missing
    except Exception:
        return [], []

# ─── Core scoring ─────────────────────────────────────────────────────────────
def score_resume_vs_job(resume_text, job_text, model):
    def chunk_text(text, size=150, overlap=30):
        words = text.split()
        if len(words) <= size:
            return [text]
        chunks = []
        i = 0
        while i < len(words):
            chunks.append(" ".join(words[i:i + size]))
            i += size - overlap
        return chunks

    resume_chunks = chunk_text(resume_text)
    job_chunks = chunk_text(job_text)

    all_texts = resume_chunks + job_chunks
    all_embs = model.encode(
        all_texts,
        normalize_embeddings=True,
        convert_to_numpy=True,
        show_progress_bar=False
    )

    r_embs = all_embs[:len(resume_chunks)]
    j_embs = all_embs[len(resume_chunks):]

    sim_matrix = cosine_similarity(j_embs, r_embs)
    best_per_job = sim_matrix.max(axis=1)
    embedding_score = float(best_per_job.mean())

    present, missing = top_keywords(job_text, resume_text, top_k=30)
    total = len(present) + len(missing)
    keyword_score = len(present) / total if total > 0 else 0.0

    final_score = (0.65 * embedding_score) + (0.35 * keyword_score)
    return final_score, present, missing

# ─── Resume tailoring advice ──────────────────────────────────────────────────
def generate_tailoring_advice(present, missing, resume_text, job_text, title="this role", resume_text_raw=None):
    advice = []
    present = clean_keywords(present, limit=12)
    missing = clean_keywords(missing, limit=12)
    raw = resume_text_raw if resume_text_raw else resume_text

    if missing:
        skill_terms = [k for k in missing if len(k.split()) <= 2][:4]
        phrase_terms = [k for k in missing if len(k.split()) > 2][:4]
        content_parts = ["These terms appear in the job description but not in your resume:\n"]
        if skill_terms:
            content_parts.append(f"**For your Skills section:** {', '.join(skill_terms)}")
        if phrase_terms:
            content_parts.append(f"**Weave into bullet points:** {', '.join(phrase_terms)}")
        if not skill_terms and not phrase_terms:
            content_parts.append(f"**{', '.join(missing[:8])}**")
        advice.append({
            "title": "🔑 Keywords to Add to Your Resume",
            "content": "\n\n".join(content_parts),
            "type": "keywords"
        })

    bullets = extract_resume_bullets(raw, limit=10)
    if bullets:
        audits = [audit_bullet(b) for b in bullets]
        passing = sum(1 for a in audits if a["score"] == 3)
        total_bullets = len(audits)
        lines = [f"**{passing}/{total_bullets}** bullets pass all checks (strong verb + metric + good length).\n"]
        for a in audits:
            verb_mark = "+" if a["strong_verb"] else "-"
            metric_mark = "+" if a["has_metric"] else "-"
            length_mark = "+" if a["length_ok"] else "-"
            truncated = " ".join(a["text"].split()[:18]) + ("..." if len(a["text"].split()) > 18 else "")
            lines.append(f"**[{verb_mark}] Verb  [{metric_mark}] Metric  [{length_mark}] Length**")
            lines.append(f"> {truncated}")
            if a["issues"]:
                for issue in a["issues"]:
                    lines.append(f"- {issue}")
            lines.append("")
        advice.append({
            "title": "✏️ Bullet Quality Check",
            "content": "\n".join(lines),
            "type": "bullets"
        })

    missing_skills = [k for k in missing if len(k.split()) <= 2][:6]
    if missing_skills:
        advice.append({
            "title": "🛠️ Update Your Skills Section",
            "content": f"Add these specific skills to your skills section if you have experience with them:\n\n"
                       f"**{', '.join(missing_skills)}**\n\n"
                       "Even if you have basic exposure, listing them helps pass ATS (Applicant Tracking Systems) filters.",
            "type": "skills"
        })

    if missing:
        advice.append({
            "title": "📝 Rewrite Your Summary/Objective",
            "content": "Keep this short and specific. For example:\n\n"
                       f"*'{build_summary_suggestion(title, present, missing)}'*",
            "type": "summary"
        })

    if present:
        advice.append({
            "title": "✅ What's Already Working",
            "content": "These keywords from the job description are already present in your resume — keep them prominent:\n\n"
                       f"**{', '.join(present[:12])}**",
            "type": "positive"
        })

    advice.append({
        "title": "🤖 ATS Tip",
        "content": "Most companies use Applicant Tracking Systems that scan for exact keyword matches before a human ever reads your resume. "
                   "Make sure the job title from the posting appears somewhere in your resume, and avoid putting key information only in headers, footers, or tables — ATS systems often can't read those.",
        "type": "ats"
    })

    return advice

def interpret(score_pct):
    if score_pct >= 60:
        return ("Excellent Match", "🌟", "#a6e3a1", "#1a2e1a")
    elif score_pct >= 50:
        return ("Good Match", "✅", "#89b4fa", "#1a1e2e")
    elif score_pct >= 38:
        return ("Partial Match", "🟡", "#f9e2af", "#2e2a1a")
    else:
        return ("Poor Match", "🔴", "#f38ba8", "#2e1a1a")

def compact_keywords(keywords, limit):
    return ", ".join(keywords[:limit]) if keywords else "None detected"

def render_match_cards(matches, resume_text, resume_text_raw=None):
    if not matches:
        st.warning("No distinct roles were found in the dataset for this resume.")
        return

    bucket_order = ["Best Fits", "Related Roles", "Stretch Roles"]
    buckets = {name: [] for name in bucket_order}
    for match in matches:
        buckets[fit_bucket(match["label"])].append(match)

    st.markdown("### Best Target Roles")
    summary_bits = []
    for name in bucket_order:
        if buckets[name]:
            titles = ", ".join(match["row"].get("title", "N/A") for match in buckets[name][:3])
            summary_bits.append(f"**{name}:** {titles}")
    if summary_bits:
        st.markdown("  \n".join(summary_bits))

    for bucket_name in bucket_order:
        bucket_matches = buckets[bucket_name]
        if not bucket_matches:
            continue
        st.markdown(f"### {bucket_name}")
        if bucket_name == "Best Fits":
            st.caption("Closest roles in both language and resume evidence.")
        elif bucket_name == "Related Roles":
            st.caption("Reasonable adjacent roles that may need clearer tailoring.")
        else:
            st.caption("Distinct but lower-fit roles that still share some overlapping themes.")

        for rank, match in enumerate(bucket_matches, 1):
            row = match["row"]
            present = match["present"]
            missing = match["missing"]
            label = match["label"]
            emoji = match["emoji"]
            text_color = match["text_color"]
            bg_color = match["bg_color"]
            why = match["why"]
            skills = summarize_skills(row.get("skills", ""), limit=5)

            st.markdown(f"""
            <div class="result-card">
                <div class="result-head">
                    <div>
                        <div class="result-title">{row.get('title', 'N/A')}</div>
                        <div class="dataset-badge" style="background:{bg_color}; color:{text_color}; border: 1px solid {text_color}55;">
                            {emoji} {label}
                        </div>
                    </div>
                </div>
                <div class="result-meta">
                    <strong>Why this match:</strong> {why}<br/>
                    <strong>Role summary:</strong> {role_summary(row)}<br/>
                    <strong>Core skills:</strong> {', '.join(skills) if skills else 'Not provided'}<br/>
                    <strong>Strongest overlaps:</strong> {compact_keywords(present, 3)}<br/>
                    <strong>Biggest gaps:</strong> {compact_keywords(missing, 3)}
                </div>
            </div>
            """, unsafe_allow_html=True)

            with st.expander(f"See tailoring advice for {row.get('title', 'this role')}", expanded=(bucket_name == "Best Fits" and rank == 1)):
                st.markdown(f"""
                <div class="dataset-badge" style="background:{bg_color}; color:{text_color}; border: 1px solid {text_color}55;">
                    {emoji} {label}
                </div>
                """, unsafe_allow_html=True)
                st.markdown(f"**Top matching title:** {row.get('title', 'N/A')}")
                st.markdown(f"**Why it matched:** {why}")
                advice_list = generate_tailoring_advice(
                    present,
                    missing,
                    resume_text,
                    row.get("master_text", ""),
                    title=row.get("title", "this role"),
                    resume_text_raw=resume_text_raw,
                )
                for advice in advice_list:
                    st.markdown(f"**{advice['title']}**")
                    st.markdown(advice["content"])
                    st.markdown("")

# ─── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(page_title="Resume Reviewer", layout="wide")

st.markdown("""
<style>
    .verdict-card {
        border-radius: 16px;
        padding: 40px;
        text-align: center;
        margin: 20px 0;
    }
    .verdict-emoji { font-size: 56px; margin-bottom: 12px; }
    .verdict-label { font-size: 36px; font-weight: 800; margin-bottom: 8px; }
    .verdict-sub { font-size: 16px; opacity: 0.85; }
    .advice-card {
        background: #1e1e2e;
        border: 1px solid #313244;
        border-radius: 12px;
        padding: 20px 24px;
        margin: 12px 0;
    }
    .advice-title {
        font-size: 17px;
        font-weight: 700;
        color: #cdd6f4;
        margin-bottom: 10px;
    }
    .advice-body {
        font-size: 14px;
        color: #a6adc8;
        line-height: 1.7;
    }
    .tag-present {
        display: inline-block;
        background: #a6e3a122;
        color: #a6e3a1;
        border: 1px solid #a6e3a144;
        border-radius: 6px;
        padding: 3px 10px;
        margin: 3px;
        font-size: 13px;
    }
    .tag-missing {
        display: inline-block;
        background: #f38ba822;
        color: #f38ba8;
        border: 1px solid #f38ba844;
        border-radius: 6px;
        padding: 3px 10px;
        margin: 3px;
        font-size: 13px;
    }
    .tag-med {
        display: inline-block;
        background: #f9e2af22;
        color: #f9e2af;
        border: 1px solid #f9e2af44;
        border-radius: 6px;
        padding: 3px 10px;
        margin: 3px;
        font-size: 13px;
    }
    .tag-low {
        display: inline-block;
        background: #6c708222;
        color: #6c7082;
        border: 1px solid #6c708244;
        border-radius: 6px;
        padding: 3px 10px;
        margin: 3px;
        font-size: 13px;
    }
    .dataset-badge {
        border-radius: 8px;
        padding: 6px 16px;
        font-weight: 700;
        font-size: 15px;
        display: inline-block;
        margin-bottom: 12px;
    }
    .result-card {
        background: linear-gradient(180deg, #111827 0%, #0b1220 100%);
        border: 1px solid #2b3548;
        border-radius: 16px;
        padding: 20px 22px;
        margin: 14px 0;
    }
    .result-head {
        display: flex;
        justify-content: space-between;
        gap: 16px;
        align-items: center;
        flex-wrap: wrap;
        margin-bottom: 12px;
    }
    .result-title {
        font-size: 24px;
        font-weight: 800;
        margin: 0;
    }
    .result-meta {
        color: #cbd5e1;
        line-height: 1.6;
        font-size: 15px;
    }
    .result-meta strong {
        color: #f8fafc;
    }
</style>
""", unsafe_allow_html=True)

st.title("Resume ↔ Job Match")

# ─── Sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Settings")
    top_n = st.slider("Top N job matches (dataset mode)", 1, 10, 5)
    show_debug = st.checkbox("Show debug preview", value=False)

# ─── Load resources ───────────────────────────────────────────────────────────
model = load_model()
jobs_emb, jobs_meta = load_job_data()

if jobs_emb is None:
    st.warning("⚠️ `jobs_emb.npy` and `jobs_metadata.csv` not found. Run `backend.py` first, then relaunch.")

# ─── Input section ────────────────────────────────────────────────────────────
col1, col2 = st.columns(2, gap="large")

with col1:
    st.subheader("Resume")
    resume_mode = st.radio("Input method", ["Paste text", "Upload file"], horizontal=True)
    resume_text = ""
    if resume_mode == "Paste text":
        resume_text = st.text_area("Paste your resume", height=320, placeholder="Paste resume content here...")
    else:
        up = st.file_uploader("Upload (PDF / DOCX / TXT)", type=["pdf", "docx", "txt"])
        if up:
            raw = up.read()
            if up.name.lower().endswith(".pdf"):
                resume_text = read_pdf(raw)
            elif up.name.lower().endswith(".docx"):
                resume_text = read_docx(raw)
            else:
                resume_text = raw.decode("utf-8", errors="ignore")
            if resume_text:
                st.success(f"Loaded {len(resume_text.split())} words from {up.name}")
            else:
                st.error("Could not extract text from file. Try copy-pasting instead.")

with col2:
    st.subheader("Job Description (optional)")
    st.caption("Paste a specific job to compare directly — or leave blank to search your full dataset.")
    job_text = st.text_area("Paste job description", height=320, placeholder="Paste job posting here...")

resume_text_raw = resume_text  # preserve newlines for bullet/section extraction
resume_text = clean_text(resume_text)
job_text = clean_text(job_text)

run = st.button("Analyze", type="primary", use_container_width=True)

# ─── Analysis ─────────────────────────────────────────────────────────────────
if run:
    if not resume_text:
        st.error("Please provide your resume text.")
        st.stop()

    if len(resume_text.split()) < 20:
        st.error("Resume text is too short — make sure the file was parsed correctly.")
        st.stop()

    st.markdown("---")

    # ── Mode A: specific job description pasted ───────────────────────────────
    if job_text:
        if len(job_text.split()) < 10:
            st.error("Job description is too short to analyze.")
            st.stop()

        with st.spinner("Analyzing match..."):
            final_score, present, missing = score_resume_vs_job(resume_text, job_text, model)

        score_pct = round(final_score * 100, 1)
        label, emoji, text_color, bg_color = interpret(score_pct)
        match_reason = build_match_reason(
            {"title": "this job", "skills": "", "description": job_text},
            present,
            missing,
            final_score,
            len(present) / max(1, (len(present) + len(missing)))
        )

        # Verdict card
        st.markdown(f"""
        <div class="verdict-card" style="background:{bg_color}; border: 2px solid {text_color}55;">
            <div class="verdict-emoji">{emoji}</div>
            <div class="verdict-label" style="color:{text_color};">{label}</div>
            <div class="verdict-sub" style="color:{text_color};">
                This resume is a <strong>{label.lower()}</strong> for this job description.
            </div>
        </div>
        """, unsafe_allow_html=True)

        # ── Section-level scoring ────────────────────────────────────────────
        sections = extract_sections(resume_text_raw)
        if sections:
            section_scores = score_sections(sections, job_text, model)
            if section_scores:
                st.markdown("### 📊 Section-Level Match Breakdown")
                st.caption("How each section of your resume matches the job description.")
                section_display_names = {
                    "summary": "Summary / Objective",
                    "experience": "Experience",
                    "skills": "Skills",
                    "education": "Education",
                    "projects": "Projects",
                }
                for sec_name, sec_score in sorted(section_scores.items(), key=lambda x: x[1], reverse=True):
                    display_name = section_display_names.get(sec_name, sec_name.title())
                    if sec_score >= 50:
                        bar_color = "#a6e3a1"
                    elif sec_score >= 35:
                        bar_color = "#f9e2af"
                    else:
                        bar_color = "#f38ba8"
                    st.markdown(f"**{display_name}** — {sec_score}%")
                    st.progress(min(sec_score / 100.0, 1.0))
        else:
            st.info("Section-level breakdown requires clearly labeled sections (e.g. 'Experience', 'Skills') in your resume.")

        st.markdown("---")

        # ── Keyword tags ──────────────────────────────────────────────────────
        st.markdown(f"**Strongest overlaps:** {compact_keywords(present, 3)}")
        st.markdown(f"**Biggest gaps:** {compact_keywords(missing, 3)}")

        left, right = st.columns(2, gap="large")
        with left:
            st.subheader(f"✅ Keywords Present ({len(present)})")
            if present:
                tags = "".join(f'<span class="tag-present">{k}</span>' for k in present[:25])
                st.markdown(tags, unsafe_allow_html=True)
            else:
                st.write("None detected.")
        with right:
            st.subheader(f"❌ Keywords Missing ({len(missing)})")
            if missing:
                if jobs_emb is not None:
                    resume_emb_vec = model.encode(
                        [resume_text],
                        normalize_embeddings=True,
                        convert_to_numpy=True,
                        show_progress_bar=False,
                    )[0]
                    prioritized = prioritize_missing_keywords(missing, resume_emb_vec, jobs_emb, jobs_meta)
                    for priority_label, css_class, priority_desc in [
                        ("HIGH", "tag-missing", "Common across similar jobs — add these first"),
                        ("MED", "tag-med", "Appears in some similar jobs"),
                        ("LOW", "tag-low", "Specific to this posting"),
                    ]:
                        group = [kw for kw, _count, p in prioritized if p == priority_label]
                        if group:
                            st.markdown(f"**{priority_label}** — {priority_desc}")
                            tags = "".join(
                                f'<span class="{css_class}">{kw}</span>'
                                for kw in group
                            )
                            st.markdown(tags, unsafe_allow_html=True)
                else:
                    tags = "".join(f'<span class="tag-missing">{k}</span>' for k in missing[:25])
                    st.markdown(tags, unsafe_allow_html=True)
            else:
                st.write("Great — most key terms found!")

        st.markdown("---")

        # ── Tailoring advice ──────────────────────────────────────────────────
        st.subheader("📋 How to Tailor Your Resume for This Job")
        st.caption("Specific, actionable steps to improve your match for this role.")

        advice_list = generate_tailoring_advice(present, missing, resume_text, job_text, title="Target Role", resume_text_raw=resume_text_raw)

        for advice in advice_list:
            with st.expander(advice["title"], expanded=True):
                st.markdown(advice["content"])

    # ── Mode B: search the full pre-computed dataset ──────────────────────────
    elif jobs_emb is not None:
        with st.spinner(f"Searching {len(jobs_emb):,} jobs in your dataset..."):
            resume_emb_vec = model.encode(
                [resume_text],
                normalize_embeddings=True,
                convert_to_numpy=True
            )[0]
            sims = cosine_similarity(resume_emb_vec.reshape(1, -1), jobs_emb)[0]
            candidate_idx = select_candidate_pool(sims, pool_size=max(300, top_n * 40))

        st.subheader(f"Top {top_n} Matching Jobs from Your Dataset")
        st.caption("Results are rescored on a larger candidate pool, then de-duplicated by role family and grouped by fit tier.")

        ranked_matches = []
        for idx in candidate_idx:
            raw_sim = sims[idx]
            row = jobs_meta.iloc[idx]
            job_master = row.get("master_text", "")

            present, missing = top_keywords(job_master, resume_text, top_k=30)
            total = len(present) + len(missing)
            kw_score = len(present) / total if total > 0 else 0.0
            blended = round(((0.65 * raw_sim) + (0.35 * kw_score)) * 100, 1)
            label, emoji, text_color, bg_color = interpret(blended)

            ranked_matches.append({
                "idx": idx,
                "row": row,
                "present": present,
                "missing": missing,
                "blended": blended,
                "label": label,
                "emoji": emoji,
                "text_color": text_color,
                "bg_color": bg_color,
                "why": build_match_reason(row, present, missing, raw_sim, kw_score),
            })

        ranked_matches.sort(key=lambda match: match["blended"], reverse=True)
        final_matches = select_diverse_matches_from_ranked(ranked_matches, top_n=top_n)
        render_match_cards(final_matches, resume_text, resume_text_raw=resume_text_raw)

    else:
        st.error("No job description pasted and no dataset loaded. Run `backend.py` first.")

    # ── Debug ─────────────────────────────────────────────────────────────────
    if show_debug:
        st.markdown("---")
        st.subheader("Debug")
        st.caption(f"Resume: {len(resume_text.split())} words")
        st.write(resume_text[:1000] + ("..." if len(resume_text) > 1000 else ""))
        if job_text:
            st.caption(f"Job: {len(job_text.split())} words")
            st.write(job_text[:1000] + ("..." if len(job_text) > 1000 else ""))

else:
    st.info("Upload your resume and optionally paste a job description, then click **Analyze**.")
