# -*- coding: utf-8 -*-
"""ResumeReviewer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpIu6pySYODd2vksc3hT5g4C5AayoJlk

**Importing the datasets**
"""

import kagglehub

# Download latest version
path1 = kagglehub.dataset_download("ravindrasinghrana/job-description-dataset")

print("Path to dataset files:", path1)

import kagglehub
path2 = kagglehub.dataset_download("kawsertalukder/resume-screening-dataset4500")
print("Path to dataset files:", path2)

"""**Cleaning the datasets**"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Scikit-learn will be imported as needed for specific tasks to avoid importing the entire library if only a small part is used.

import pandas as pd

# Storing the dataset into a dataframe
df1 = pd.read_csv(path1 + "/job_descriptions.csv")

df1_raw = df1.copy()

df1 = df1_raw.copy()

COLS = ["title", "description", "qualifications", "skills", "responsibilities", "experience_years"]

rename = {"Job Title": "title", "Job Description": "description", "skills": "skills", "Experience": "experience_years", "Responsibilities": "responsibilities", "Qualifications": "qualifications"}

df1_std = df1.rename(columns=rename)

columns_to_drop = ['Job Id', 'Salary Range', 'location', 'Country', 'latitude', 'longitude', 'Company Size', 'Job Posting Date', 'Preference', 'Contact Person', 'Contact', 'Job Portal', 'Benefits', 'Company', 'Company Profile', 'Role', 'Work Type']
df1_std = df1_std.drop(columns_to_drop, axis=1)

df1_reduced = df1_std.sample(n=20_000, random_state=42)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df2 = pd.read_csv(path2 + "/ml_resume_dataset_4500.csv")

df2_raw = df2.copy()
df2 = df2_raw.copy()

columns = ["years experience", "highest degree", "skills", "current title", "raw text"]

df2_raw = df2.copy()

re_columns = {"years_experience":"years experience", "highest_degree": "highest degree", "skills":"skills", "current_title":"current title", "raw_text":"raw text"}

new_df2 = df2.rename(columns=re_columns)

drop_columns = ["name", "has_portfolio", "label"]

df2_clean = (
    df2_raw
      .rename(columns=re_columns)
      .drop(columns=[c for c in drop_columns if c in df2_raw.columns], errors="ignore")
)

df2_clean.shape, df2_clean.columns
df2_clean.head()

df1_reduced[COLS] = df1_reduced[COLS].astype(str)

SEP = "\n"

df1_reduced["master_text"] = (
    df1_reduced["title"] + " " +
    df1_reduced["skills"] + " " +
    df1_reduced["skills"] + " " +
    df1_reduced["skills"] + " " +
    df1_reduced["responsibilities"] + " " +
    df1_reduced["responsibilities"] + " " +
    df1_reduced["responsibilities"] + " " +
    df1_reduced["qualifications"] + " " +
    df1_reduced["qualifications"] + " " +
    df1_reduced["description"] + " " +
    df1_reduced["experience_years"]
)

df1_final = df1_reduced["master_text"]

print(df1_final)

df2_clean["model_text"] = (
    df2_clean["current title"].astype(str) + " " +
    df2_clean["skills"].astype(str) + " " +
    df2_clean["skills"].astype(str) + " " +
    df2_clean["skills"].astype(str) + " " +
    df2_clean["raw text"].astype(str) + " " +
    df2_clean["highest degree"].astype(str) + " " +
    df2_clean["years experience"].astype(str)
)

df2_clean[["id", "model_text"]].head()

"""**Sentence Embeddings**"""

import sentence_transformers
from sentence_transformers import SentenceTransformer

# Load the model
ST_model = SentenceTransformer('all-MiniLM-L6-v2')

jobs_data = df1_final.astype(str).tolist()

jobs_emb = ST_model.encode(
    jobs_data,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

np.save("jobs_emb.npy", jobs_emb)

import sentence_transformers
from sentence_transformers import SentenceTransformer

# Load the model
ST_model = SentenceTransformer('all-MiniLM-L6-v2')

resume_data = df2_clean["model_text"].astype(str).tolist()

resume_emb = ST_model.encode(
    resume_data,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

np.save("resume_emb.npy", resume_emb)

# ADD THESE TWO LINES after np.save("jobs_emb.npy", jobs_emb)
df1_reduced[["title", "description", "skills", "master_text"]].reset_index(drop=True).to_csv("jobs_metadata.csv", index=False)
print("jobs_metadata.csv saved!")

# Commented out IPython magic to ensure Python compatibility.

import streamlit as st
import pandas as pd

st.set_page_config(page_title="Resume Reviewer", layout="wide")
st.title("Resume Reviewer")

st.write("Upload the resume")
uploaded = st.file_uploader("Upload", type=["csv"]) # Make the user upload a pdf, not a csv

if uploaded:
    df = pd.read_csv(uploaded).fillna("")
    st.write("Columns:", list(df.columns))

    if "model_text" not in df.columns and all(c in df.columns for c in
        ["current title","skills","highest degree","years experience","raw text"]):
        df["model_text"] = (
            "TITLE: " + df["current title"].astype(str) + " "
            "SKILLS: " + df["skills"].astype(str) + " "
            "SKILLS: " + df["skills"].astype(str) + " "
            "DEGREE: " + df["highest degree"].astype(str) + " "
            "EXPERIENCE_YEARS: " + df["years experience"].astype(str) + " "
            "RAW: " + df["raw text"].astype(str)
        )

    idx = st.number_input("Row index", 0, len(df)-1, 0)
    st.text_area("model_text", df.loc[idx, "model_text"], height=300)

